version: 2

models:
  - name: stg_local_bike__brands
    description: "This model contains information about the different brands names of the differents bikes"
    columns:
      - name: brand_id
        description: "Primary key, unique identifier for each brand"
        tests:
            - unique
            - not_null

  - name: stg_local_bike__orders
    description: "This model contains the informations about the bikes orders."
    columns:
      - name: order_id
        description: "Primary key, unique identifier for each order."
        tests:
            - unique
            - not_null
      - name: customer_id
        description: "Foreign key linking the order to the customer who placed it."
        tests:
          - relationships:
              name: customer_id_id_foreign_key_in_stg_local_bike__orders
              to: ref('stg_local_bike__customers')
              field: customer_id
      - name: store_id
        description: "Foreign key linking the order to the store where the bike came from."
        tests:
          - relationships:
              name: store_id_id_foreign_key_in_stg_local_bike__orders
              to: ref('stg_local_bike__stores')
              field: store_id
      - name: staff_id
        description: "Foreign key linking the order to the staff who sold it."
        tests:
          - relationships:
              name: staff_id_id_foreign_key_in_stg_local_bike__orders
              to: ref('stg_local_bike__staffs')
              field: staff_id

  - name: stg_local_bike__order_items
    description: "This model contains information about each item included in an order, including its price, quantity, and discount."
    columns:
      - name: order_item_id
        description: "Primary key, unique identifier for each order item. Generated by concatenating order_id and item_id"
        tests:
            - unique
            - not_null
      - name: order_id
        description: "Foreign key linking the order item to the corresponding order."
        tests:
          - relationships:
              name: order_id_id_foreign_key_in_stg_local_bike__order_items
              to: ref('stg_local_bike__orders')
              field: order_id
      - name: product_id
        description: "Foreign key linking the order item to the corresponding product."
        tests:
          - relationships:
              name: product_id_id_foreign_key_in_stg_local_bike__order_items
              to: ref('stg_local_bike__products')
              field: product_id

  - name: stg_local_bike__customers
    description: "This model contains information about the customers."
    columns:
      - name: customer_id
        description: "Primary key, unique identifier for each customer."
        tests:
            - unique
            - not_null

  - name: stg_local_bike__categories
    description: "This model contains the name of the bikes categories"
    columns:
      - name: category_id
        description: "Primary key, unique identifier for each category."
        tests:
            - unique
            - not_null

  - name: stg_local_bike__products
    description: "This model contains information about the products."
    columns:
      - name: product_id
        description: "Primary key, unique identifier for each product."
        tests:
            - unique
            - not_null
      - name: brand_id
        description: "Foreign key linking the product item to the corresponding brand."
        tests:
          - relationships:
              name: brand_id_id_foreign_key_in_stg_local_bike__products
              to: ref('stg_local_bike__brands')
              field: brand_id
      - name: category_id
        description: "Foreign key linking the product item to the corresponding category."
        tests:
          - relationships:
              name: category_id_id_foreign_key_in_stg_local_bike__products
              to: ref('stg_local_bike__categories')
              field: category_id

  - name: stg_local_bike__staffs
    description: "This model contains staff-related information, including where they work."
    columns:
      - name: staff_id
        description: "Primary key, unique identifier for each staff."
        tests:
            - unique
            - not_null
      - name: store_id
        description: "Foreign key linking the staff to the corresponding store he work."
        tests:
          - relationships:
              name: store_id_id_foreign_key_in_stg_local_bike__products
              to: ref('stg_local_bike__stores')
              field: store_id      

  - name: stg_local_bike__stocks
    description: "This model contains the stock quantity for each store."
    columns:
      - name: stock_id
        description: "Primary key, unique identifier for each stock: generated by concatenating store_id and product_id."
        tests:
            - unique
            - not_null
      - name: store_id
        description: "Foreign key linking the stock store to the corresponding store."
        tests:
          - relationships:
              name: store_id_id_foreign_key_in_stg_local_bike__stocks
              to: ref('stg_local_bike__stores')
              field: store_id
      - name: product_id
        description: "Foreign key linking the stock product to the corresponding product."
        tests:
          - relationships:
              name: product_id_id_foreign_key_in_stg_local_bike__stocks
              to: ref('stg_local_bike__products')
              field: product_id

  - name: stg_local_bike__stores
    description: "This model contains store-related information."
    columns:
      - name: store_id
        description: "Primary key, unique identifier for each store."
        tests:
            - unique
            - not_null
